language: generic

sudo: required
services:
  - docker

before_install:
  - docker build -t firstproj -f Dockerfile.dev .

script:
  - docker run -e CI=true firtproj npm run test -- --coverage