language: generic

sudo: required
services:
  - docker

before_install:
  - docker build -t firstproj -f Dockerfile.dev .

script:
  - docker run -e CI=true firstproj npm run test -- --coverage

deploy:
  provide: elasticbeanstalk
  region: "ap-northeast-1"
  app: "Docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-ap-northeast-1-13989246254"
  bucket_path: "Docker-react"
  on:
    branch: main

